### ISSUE TITLE
Send context

### ISSUE THREAD

**Issue by maxguzenski** [krisleech/wisper#121]
I know that this can grow in too much complexity, but what do you think if wisper could pass context/params/options to listeners ?

```ruby
class AGlobalListener
  def on_success(obj, ctx={})
     return if ctx[:role] == :admin || ctx[:skip_globals]
     # ... code ...
  end 
end
```

Then you can call your object like that:

```ruby
# Global listener
Wisper.subscribe(AGlobalListener.new)

MyService.new
    .with_context({skip_globals: true, role: :admin, user: current_user})
    .call(...)
```

This could be useful to:
* Pass context to listeners, like current_user 
* Pass adicional parameters/config
* Enable/Disable some global listeners, like Analytic listeners

**Comment by maxguzenski** [comment]
I can implement it, If you are willing to accept this feature.

**Comment by maxguzenski** [comment]
I have it working on https://github.com/maxguzenski/wisper , just need update README.

**Comment by krisleech** [comment]
Hi - What is the advantage of this over just broadcasting those same arguments to the listeners?

e.g. `broadcast(arg1, arg2, context)`.

**Comment by maxguzenski** [comment]
I use wisper to listen my ActiveRecords callbacks, and I have a lot of listener attach globally to those models. So:

```ruby
User.new(...).with_context({current_user: current_user}).save!
```

Right now, I have something like your wisper-activerecord, but modified to has "context support"... 

And the advantage is just to be an out-of-box solution. I know that maybe it is a very specific need, accept it if you think it can be util for someone else ;)

**Comment by jhoffner** [comment]
Yeah to me it seems like a highly specialized thing based off to how you handle "context" data. 

Me personally, I would look into possibly refactoring how you handle context data. For example current_user would be much better stored as a thread level variable so that you have access to it anywhere. AKA
```ruby
class UserContext
  attr_reader :user
  def initialize(user: nil)
    @user = user
  end

  def self.current
    Thread.current['user_context']
  end

  def self.current=(value)
    Thread.current['user_context'] = value
  end

  def self.with(options)
    previous = self.current
    begin
      self.current = UserContext.new(options)
      yield
    ensure
     self.current = previous
    end
  end
end
```

**Comment by maxguzenski** [comment]
Yes, for sure, that is other ways to do the same, but using Thread.current will not going to work with async listeners (like sidekiq, etc).

**Comment by krisleech** [comment]
Having to pass the context is a downside to broadcasting directly from models instead of something like a service, to which you can pass additional arguments like current_user. Like you say it is specific need so not something I feel would go in to Wisper, which is general purpose pub/sub. 

But what I might suggest is creating a new gem and linking it from the Wiki. 

I looked over your code and I think you might be able to do it without having to monkey patch Wisper. Instead of patching Registration and freinds you might be able to create a [custom broadcaster](https://github.com/krisleech/wisper/wiki/Write-custom-broadcasters) which grabs the context from the publisher and adds to the broadcast args. You would then just need to register the broadcast insteads of the default sync one (if you need async as well, then you'll need to create an async broadcaster, maybe just inheriting from an existing one).

If this works this is also a better option than monkey patching because the internal code will change dramatically for Wisper 2.0, but the broadcaster API will remain the same.

**Comment by krisleech** [comment]
Closing, please re-open if you have further comments.
