### ISSUE TITLE
Private visibility of Publisher#publish?

### ISSUE THREAD

**Issue by muellerj** [krisleech/wisper#157]
Hi there,

I stumbled across this while trying to debug `tty-prompt` with Ruby 2.4. You can find the issue here: piotrmurach/tty-prompt#35. In short: Ruby 2.4s `Forwardable` raises a warning when delegating to a private method (see https://bugs.ruby-lang.org/issues/12782). Since `Wisper::Publisher#publish` is defined private (https://github.com/krisleech/wisper/blob/master/lib/wisper/publisher.rb#L50), calling it through `Forwardable` generates a warning which messes up the escape-codes trying to manipulate the prompt.

I assume you have a good reason for making `publish` and `broadcast` private? Could you elaborate why without going to too much trouble?

If you intend to keep these private, do you have a hint how `Wisper` can be used with `Forwardable`?

Thanks for your help in advance!

**Comment by krisleech** [comment]
`publish` is private because only an object itself should publish events using data it owns. External objects shouldn't be able to invoke an event to be emitted from an object which isn't itself.

Sorry for the delay in replying, I see your issue is closed, so I will close this also. Please feel free to re-open should you need more information or to explore solutions.

**Comment by piotrmurach** [comment]
Hey Kris,

This is interesting take on the pub/sub. I'm not sure whether I understand the reasoning behind 

>External objects shouldn't be able to invoke an event to be emitted from an object which isn't itself.

I will try to persuade you to the contrary, e.i. against making `publish` private :smile:

In case of `tty-prompt`, where the issue surfaced originally, the `Reader` is a publisher and notifies all the prompts about a key being pressed. However, when you listen for events you can also `trigger` key event on prompt to propagate to prompts that are interested via the `Reader`. Since `Reader` knows how to notify all the prompts it seems reasonable to forward such events.

```ruby
prompt.on(:keypress) do |event|
  if event.value == 'j
    prompt.trigger(:keyup)
  end
end
```

> only an object itself should publish events using data it owns

I'm not sure I agree with this statement. If you follow the reasoning that `pub/sub` decouples components, it seems reasonable to expect that you can pass events that carry data between observed components. The observer pattern as far as I can tell doesn't enforce data belonging. For example, in my other library called [finite_machine](https://github.com/piotrmurach/finite_machine) I'm using observer that allows you to specify events & callbacks on the state machine and trigger these with `trigger` method that accepts the name for the event and additional data. The data isn't owned by state machine but is a property of a given event that is triggered and forwarded to the observer to propagate to any listeners.

```ruby
finite_machine.trigger(:go, 'Piotr!', 1, 2, 3)
```

I think a good example is node's `EventEmitter` that specifically has `on` method for listening and `emit` for emiting events which are both public as far as I can tell - [docs](https://nodejs.org/api/events.html)

The way I solved the problem in `tty-prompt` is to add new public method called `trigger` that wraps `publish`.

Thanks for your library!
