### ISSUE TITLE
Listener not registering with custom devise controller

### ISSUE THREAD

**Issue by whysthatso** [krisleech/wisper#163]
Rails 4.2.6
Wisper 1.6.1
Devise 4.0.1

Hey,
i've used wisper to publish an event upon updating of a devise user object (condition: specific attribute changed:

```
class User < ActiveRecord::Base
  include Wisper::Publisher
  after_update :publish_foobar_change, if: :foobar_changed?
  [...]
  private
  def publish_foobar_change
    publish(:foobar_changed, self)
  end
```

here's the publisher class i'm using:

```
class UserSubscriber
  def foobar_changed(user)
    DoSomethingService.do_it(user, :foobar_changed)
  end
end
```

Then in the custom devise controller (generated with: `rails generate devise:controllers users`), i've changed the `update` method as suggested in the wiki which caused a NoMethodError on 'String'

```
  def update
    super.subscribe(RegistrationMailer.new)                                                 
  end
```

Calling it on `resource` returned an empty set:

```
  def update
    resource.subscribe(RegistrationMailer.new)
    super                                              
  end
```

However, if i use an config/initializer the whole thing works perfectly:

```
User.subscribe(UserSubscriber.new)
```

Is there something wrong in my syntax or thinking? Is it devise?

**Comment by antulik** [comment]
Looks like it's related to devise and the way `update` override works. 

you can try temporary global listeners inside controller action

```ruby
def update 
  User.subscribe(UserSubscriber.new) do 
    super
  end 
end
```

**Comment by whysthatso** [comment]
ok, i'll just leave this here. if this becomes a problem, somebody might reopen the issue.

i've settled on the entry in an initializers file as it might be a nice way of having all the broadcasters and subscribers 'catalogued' in a way

**Comment by krisleech** [comment]
I haven't used Devise in quite a while, but I do not think the actions return the resource (active record model) and subscribing *after* super is called would mean it is too late because the event would already have been broadcast before the listener is subscribed. In the wiki example the `#build_resource` method is used to do the subscribing not the action method: https://github.com/krisleech/wisper/wiki/Devise

Using a temporary global subscription as suggested by @antulik would also work as would a global subscription in an initializer as you suggested.

I'm surprised that the second example, `resource.subscribe(....)`, does not work.

If you need more help could you open a Stackoverflow issue tagged with Wisper, you'll get more eyeballs :)
