### ISSUE TITLE
Wisper vs WisperNext vs Ma

### ISSUE THREAD

**Issue by veeral-patel** [krisleech/wisper#178]
Hi - I'm developing an events API for my Rails app and I'm conflicted between these three choices. I've read their READMEs but I don't know what's the right choice for me. Any suggestions?

**Comment by krisleech** [comment]
Wisper has been around since 2013 and is heavily used in production.

WisperNext is the next evolution of Wisper and was only recently released. It should be considered for new projects if you can tolerate some risk in return for a more flexible product. The risk being that it hasn't been tested extensively in production yet.

Ma is built on top of WisperNext and offers Event objects. 

One thing I should mention is that WisperNext (and thus Ma too) does not have any async adapters yet, they need to be written, e.g. for sidekiq.

Hope this helps.

**Comment by veeral-patel** [comment]
@krisleech Thanks!

1. Any notable advantages of WisperNext over Wisper? At this point it seems like Wisper is the de facto best option.

2. Sorry, what are some use cases for event objects? When would I need them?

Thank you!

**Comment by krisleech** [comment]
> Any notable advantages of WisperNext over Wisper? At this point it seems like Wisper is the de facto best option.

Because of the way it is designed it has more potential. In Wisper the publisher does all the work, in WisperNext the publisher just calls `#on_event` on each subscriber. The subscriber the decides how it wishes to handle the event (e.g. call another method, use async, transform the payload, ignore etc.). It is easier to build new functionality on. 

If you are happy with the Wisper feature set it s a good choice. It isn't going anywhere.

> Sorry, what are some use cases for event objects? When would I need them?

Event objects are good for adding explicit structure to events. In Wisper/WisperNext you can broadcast arbitrary objects. Event objects add typing, so instead of listener depending on an event name they depend on a concrete class (the event class).

**Comment by jdickey** [comment]
@krisleech Late to the party as usual. We've used Wisper for quite some time, but looking at the README for Ma indicates that async adapters are [a TODO](https://gitlab.com/kris.leech/ma#handling-events-asynchronously)? How does the synchronous performance of Ma compare to that of Wisper?

**Comment by krisleech** [comment]
@jdickey I'm leaving it up to others to build and maintain the async adapters for WisperNext (which are used by Ma without change). 

Async performance-wise I have not conducted any benchmarks.

**Comment by woto** [comment]
It's very frustrating that this explanation hadn't described near
> For greenfield applications you might also be interested in WisperNext and Ma.

I would like to see it there

Anyway much appreciate your work. Thank you!
